travis:
  secure:
    BINSTAR_TOKEN: G2Vqo8IgrW7BLJmrCClXLD2B82k0LPp2wZSwcQhvnVb3vj1HpvKpj0MYidT9UWPE3QGFGY7wWXawoHn8hBW32BXMmiNQJOPHFbdmxm7trlch2WADS6g7/NRJfogArgYfcRMHLXDP87Ivrcxoy2wqTLW328+9r8qWrzBSz7YOJwTebbudLCKRp5Qp9+EqH0DBx2XtWJEJz0p0v10Nxp2uv2OOtreMk1q+FPGIGjihURbvMSMwrxknw3hrKBnZHmBWyi2ptQcfaonu3B4RPjqjRIU6WZ0fuBYi8HXd4nBVuyYs6El5rlHh0qKxoPgWMZjoKUUzV63QJtf9v4yI1DSe+hU8Q46n6jvbtEeGHVVlvY+U4KZCBjA/oJ0IcajvzAOFZWTNWbj+FvUGEKGUWshXFxi/9bxet/7Y+mBTs5lR4s0CdevDnVNh9xy44QRKEPGAmdwgTsZPPGzS8dqZEjj/q1IuJeBNtSUWpYuibM65zWx56WdLXWtTWPsY19WgfWlzEIEx8FggAUmrh8g441wkCxfUxDjEaok0g6I316XvUGTR5K69fY9BFEZUZZh0ZvF8kq0Fl9tLrO8ttw9MM+u+6/zjVGR9zDiDbfVIHx9bXNYj9Z6E23JyiauvIZ7mder1o8jqgYOlDJz9x5qFF844lo5Yb27z52DbNZFPbkCQCVs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
